.TH DMENU 1 dmenu\-VERSION
.SH НАЗВА
dmenu \- динамічне меню
.SH ПІДСУМОК
.B dmenu
.RB [ \-FSbfirvs ]
.RB [ \-l
.IR кількість ]
.RB [ \-h
.IR висота ]
.RB [ \-p
.IR питання ]
.RB [ \-m
.IR монітор ]
.RB [ \-w
.IR id_вікна ]
.RB [ \-it
.IR текст ]
.RB [ \-n
.IR номер ]
.P
.BR dmenu_run " ..."
.SH ОПИС
.B dmenu
\- це динамічне меню для X, яке приймає список пунктів з stdin,
по одному на рядок.
Після того, як користувач обере один з пунктів та натисне Return,
його вибір буде виведено в stdout а dmenu завершить роботу.
Якщо почати набирати текст, то кількість пунктів у меню буде скорочуватись до тих,
які співпадають із введеним текстом.
.P
.B dmenu_run
\- це скрипт, що використовується
.IR dwm (1).
Він виводить перелік програм на $PATH користувача й запускає вибір його $SHELL.
.SH КЛЮЧІ
.TP
.B \-b
відображувати знизу екрану
.TP
.B \-f
dmenu зчитує клавіатуру перед stdin, якщо читає не з tty.
Так швидше, але X буде заблокованим поки stdin не досягне кінця файлу.
.TP
.B \-s
dmenu matches menu items case sensitively.
.TP
.B \-S
не впорядковувати пункти після звірювання.
.TP
.B \-r
вимикає ctrl-return та shift-return і тим забеспечує відсутність множинного вибору.
.TP
.BI \-l " lines"
вертикальний список із вказаною кількістю рядків.
.TP
.BI \-h " висота"
висота рядків у пікселах.
Не може бути менше восьми.
.TP
.BI \-m " монітор"
вибрати монітор, починаючи з нуля.
.TP
.BI \-p " запитання"
визначає текст, що буде написаний зліва від поля вводу.
.TP
.B \-v
виводить версію програми.
.TP
.BI \-w " id_вікна"
запустити всередині вікна із вказаним id.
.TP
.BI \-n " номер"
Почати з виділеним пунктом під певним номером, починаючи з нуля.
.TP
.BI \-it " текст".
Почати з уже введеним текстом.
.SH ВИКОРИСТАННЯ
Для використання dmenu достатньо лише клавіатури.
Можна рухатись по меню за стрілочками, page up, page down, home та end.
.TP
.B Tab
Зкопіювати вибраний пункт до поля вводу.
.TP
.B Return
Зробити вибір та вийти.
.TP
.B Ctrl-Return
Вибрати пункт але не виходити.
.TP
.B Shift\-Return
Підтвердити вибір. Виводить обрані пункти до stdout та завершує роботу.
.TP
.B Escape
Вийти не виділивши жодного пункту, повернувши помилку.
.TP
.B Ctrl-Left
Перемістити курсор на початок слова
.TP
.B Ctrl-Right
Перемістити курсор в кінець слова
.TP
.B C\-a
На початок
.TP
.B C\-b
Ліворуч
.TP
.B C\-c
Вийти
.TP
.B C\-d
Видалити вправо
.TP
.B C\-e
В кінець рядка
.TP
.B C\-f
Праворуч
.TP
.B C\-g
Вийти
.TP
.B C\-h
Видалити вліво
.TP
.B C\-i
Табуляція
.TP
.B C\-j
Return
.TP
.B C\-J
Shift-Return
.TP
.B C\-k
Видалити кінець слова
.TP
.B C\-m
Return
.TP
.B C\-M
Shift-Return
.TP
.B C\-n
Вниз
.TP
.B C\-p
Вгору
.TP
.B C\-u
Видалити початок рядка
.TP
.B C\-w
Видалити початок слова
.TP
.B C\-y
Вставити з основного буферу
.TP
.B C\-Y
Вставити з X буферу обміну
.TP
.B M\-b
На початок слова
.TP
.B M\-f
В кінець слова
.TP
.B M\-g
На початок
.TP
.B M\-G
В кінкць
.TP
.B M\-h
Вгору
.TP
.B M\-j
На сторінку вниз
.TP
.B M\-k
На сторінку вгору
.TP
.B M\-l
Вниз
.SH ДИВИСЬ ТАКОЖ
.IR dwm (1),
.IR stest (1)
